# Tab modules — import each tab class here for easy access
from .merge        import MergeTab
from .split        import SplitTab
from .extract_text   import ExtractTextTab
from .extract_images import ExtractImagesTab
from .compress       import CompressTab
from .rotate         import RotateTab
from .watermark      import WatermarkTab
from .password       import PasswordTab
from .reorder        import ReorderTab
from .metadata       import MetadataTab
from .blank          import BlankTab
from .repair         import RepairTab
from .convert        import ConvertTab
from .crop           import CropTab
from .ocr            import OcrTab
from .compare        import CompareTab
from .redact         import RedactTab
from .pagenumbers    import PageNumbersTab
from .signature      import SignatureTab
from .nup            import NupTab
from .bookmarks      import BookmarksTab
